name: migraine_meter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  calendar_appbar: ^0.0.6
  table_calendar: ^3.0.8
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  quickalert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
   # Asset eklemek için assets anahtarını kullanabilirsiniz.
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/b1.png
    - assets/b2.png
    - assets/b3.png
    - assets/b4.png
    - assets/b5.png
    - assets/b6.png
    - assets/b7.png
    - assets/b8.png
    - assets/b9.png
    - assets/b10.png
    - assets/b11.png
    
